function[F] = Blackbody(v, T, r, f, NA)
    % This function returns the photon flux density F(v) for a blackbody
    % spectrum generated by a spherical source with temperature T and radius r
    % and collimated by a condenser lens of focal length R and numerical
    % aperture NA.
    
    c   = 3e8; % Speed of light
    kB  = 1.3807e-23; % Boltzmann constant
    h   = 6.6262e-34; % Planck's constant

    F = ((16 * pi * (r^2) * (v.^2)) / ((c * f)^2)) .* (1 ./ (exp((h * v) / (kB * T)) - 1)) * ((1 - sqrt(1 - (NA^2))) / (NA^2))
end